title: Amazon Review Web Scraping
description: LSE DS105M 2022/2023 Final Project
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  View Our Repository: https://github.com/dveksler02/dveksler02.github.io

color_scheme: dark

navigation: 
- {file: index.md, title: Home}
- {file: readme.md, title: Next}
