title: Amazon Web Scrapeer Tool - DS105M
description: LSE DS105M 2022/2023 Final Project
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/dveksler02/dveksler02.github.io
