title: DS105M Final Project
{: .fs-7 } 
description: LSE DS105M 2022/2023 Final Project
theme: just-the-docs

url: https://dveksler02.github.io

aux_links:
  View Our Repository: https://github.com/dveksler02/dveksler02.github.io

color_scheme: dark

back_to_top: true
back_to_top_text: "Back to top"
